### ISSUE TITLE
process.is_running always true

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#121] opened 2016-08-11 18:05 UTC
I want to have a process that is enabled, but not running.
If that is the case, if I assert process.is_running it seems to be always true.

**Comment by philpep** [comment] 2016-08-12 00:42
Hi. I don't understand (you mean service or process ?). Please explain your issue or provide an example to reproduce it. Thanks

**Comment by emayssat-ms** [comment] 2016-08-12 00:42
sorry service

**Comment by emayssat-ms** [comment] 2016-08-12 17:36
`import pytest                                                                    
                                                                                 
pytestmark = [                                                                   
    pytest.mark.os,                                                              
    # pytest.mark.debug_mode,                                                    
]                                                                                
                                                                                 
xfail = pytest.mark.xfail                                                        
imager = pytest.mark.imager                                                      
                                                                                 
                                                                                 
@pytest.mark.parametrize('name,is_running,is_enabled', [                          
    # xfail(reason='Why is this failing?')(('cron', False, True)),                
    imager(('cron', False, True)),                                                
])                                                                                
def test_if_service_ok(Service, name, is_running, is_enabled):                    
    s = Service(name)                                                             
    assert s.is_enabled == is_enabled                                             
    assert s.is_running == is_running, 'is_running seems to be always True!' `

**Comment by emayssat-ms** [comment] 2016-08-30 17:40
Were you able to duplicate the issue?

**Comment by philpep** [comment] 2016-08-31 07:42
Can you run the test with ``-vvs`` flags to you can see what command testinfra execute to test the service is running or not.

**Comment by achaussier** [comment] 2016-11-19 16:21
Hello,

FYI, a test on an "Ubuntu Trusty" service returns always True also, but it's due to the return code of the command:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service ufw stop
ufw stop/waiting
vagrant@vagrant-ubuntu-trusty-64:~$ service ufw status
ufw stop/waiting
vagrant@vagrant-ubuntu-trusty-64:~$ echo $?
0
```

**Comment by philpep** [comment] 2016-12-04 10:34
Closing this since I cannot reproduce the issue (maybe an bug in specific init script ?)

**Closed by philpep** 2016-12-04 10:34 UTC
